### ISSUE TITLE
Item count stays at double digits when going from 10 to 9

### ISSUE THREAD

**Issue by ghost** [Vulcalien/minicraft-gba#3] opened 2023-04-02 16:19 UTC
I was playing on an Everdrive GBA flash cart on my Game Boy Micro when I noticed this issue.
When an held item's item count goes from 10 to 9, The game will still show 2 digits
Example: If you have 10 apples and eat one then the item count will show 90 (instead of 9). If you continue to eat them, it'll show 80, 70, 60, etc...
I tested this with eating apples and placing dirt. The bug may also occur when going from triple digits to double digits but I haven't tested that.

**Comment by Vulcalien** [comment] 2023-04-02 16:36
Hey! Thanks for playing the game, and for reporting this bug!

I can confirm it, and I'm not sure how I never found this bug. Luckily, it's only a visual error.
What is happening is that until the item is changed, I'm not clearing that area where the name and count for the item goes.
By this logic, I also expect triple digits to have the same problem.

Thanks again! I'll get that fixed, and if another version comes out, it should work.

**Comment by ghost** [comment] 2023-04-02 16:52
Sweet! Can't wait :)
And thank you so much for making this port! I couldn't run minecraft as a kid so I played this game all the time. I've been using my micro to play it during my work breaks and it's simply amazing!

**Comment by Vulcalien** [comment] 2023-04-02 23:11
It should now be fixed by ec827842235451d88d6c66a8fd0f9a46ebffd24e!

I'm glad this port of the game makes it easy for you to play it! Since you are running it on a real GBA, be sure to use version 1.1, as there is a real hardware-only bug with lantern light. (the save files are 100% compatible).

**Closed as completed by Vulcalien** 2023-04-02 23:11 UTC

**Comment by ghost** [comment] 2023-04-25 05:01
Can you give me a step-by-step guide on how to build the rom? I try running "arm-none-eabi-gcc make" in the directory but it doesn't work. I'm a bit nooby at this stuff.
I'm getting:
arm-none-eabi-gcc: error: make: No such file or directory
arm-none-eabi-gcc: fatal error: no input files
compilation terminated.

**Comment by Vulcalien** [comment] 2023-04-25 12:14
Oh sure, the command is simply `make`. Since you already have arm-none-eabi-gcc installed, it should compile without trouble.

You'll find the `.gba` file in the bin folder.
